### ISSUE TITLE
System Tray programs not quiting

### ISSUE THREAD

**Issue by nicolasgut88** [UbuntuBudgie/budgie-desktop-environment#78]
when i click quit in any system tray program it does not quit, but if i press enter it does quit. This is not a critical issue, just an enhancement problem.

**Comment by nickdonnelly** [comment]
It seems to me that in order to get them to take my input I have to click the icon and the menu with the same button. In other words, if I right click to open the menu for a tray application, I have to right click on the menu item. If I left click to open the menu, I have to left click the menu item.

This is extremely annoying, I should be able to left click without the menu opening at all, just like a normal tray application on every other system...This doesn't happen with Budgie on Solus. Something to do with AppIndicator?

**Comment by fossfreedom** [comment]
@nickdonnelly maybe - check in your panel where you are clicking - move the appindicator to another position.

**Comment by nickdonnelly** [comment]
@fossfreedom I tried this to no avail, ubfortunately. Perhaps it's my system only but I just got rid of the applet all together and am using the default system tray which behvaes correctly in my case.

**Comment by fossfreedom** [comment]
Same as this. https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/12
