### ISSUE TITLE
problems with multiple screens

### ISSUE THREAD

**Issue by violoncelloCH** [UbuntuBudgie/budgie-desktop-environment#95]
If I have multiple screens and place the primary display below an other one, the reserved space for the top bar is reserved at the screen above the primary display.
So I get a transparent bar at the top display which I can't use, I can not place a window over it.
And in the same time if I maximize a window on the primary display, the toolbar disappears behind the top bar, making it hard to minimize or replace the window.

**Comment by violoncelloCH** [comment]
maybe this is a more general issue with gnome?

**Comment by violoncelloCH** [comment]
~~ah and I have to add, I use displaylink drivers for my docking station and the monitors...~~
it's the same if I connect the monitor directly via hdmi

**Comment by fossfreedom** [comment]
This is a known issue upstream - I think it is due to the bar on the primary monitor preventing windows moving above.  You can test that theory by moving the bar to the side/bottom.

https://github.com/solus-project/budgie-desktop/issues/474

I'll close this here since you can subscribe/help out with fixes upstream.

**Comment by violoncelloCH** [comment]
Ok thank you

**Comment by violoncelloCH** [comment]
Strange... seems like the issue you mentioned describes the opposite issue which is now solved in a way it results in the symptoms I have described...
